name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: ${{ matrix.os }} - ${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # ----------------------------------------------------------------
          # LINUX Configuration
          # Uses the "linux-ninja-debug" preset we defined earlier
          # ----------------------------------------------------------------
          - os: ubuntu-latest
            configure-preset: "linux-ninja-debug"
            build-preset: "linux-ninja-debug"
            build-type: "Debug"

          # ----------------------------------------------------------------
          # WINDOWS Configuration
          # Uses "windows-msvc" (Configure) and "windows-msvc-debug" (Build)
          # Recall: MSVC is multi-config, so configuration happens at build time
          # ----------------------------------------------------------------
          - os: windows-latest
            configure-preset: "windows-msvc" 
            build-preset: "windows-msvc-debug"
            build-type: "Debug"

    steps:
    - uses: actions/checkout@v4

    # ----------------------------------------------------------------
    # 1. Setup Environment
    # ----------------------------------------------------------------
    - name: Install Ninja (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    # Ensure we have a modern CMake (3.20+) capable of understanding Presets v3
    - name: Setup CMake
      uses: jwlawles/cmake.x@v1
      with:
        cmake-version: '3.25.x'

    # ----------------------------------------------------------------
    # 2. Configure
    # This generates the build files in build/${presetName}
    # ----------------------------------------------------------------
    - name: Configure Project
      run: cmake --preset ${{ matrix.configure-preset }}

    # ----------------------------------------------------------------
    # 3. Build
    # This compiles the code. We use the --preset argument to pick up
    # the correct "buildPresets" entry (which handles Debug/Release for MSVC)
    # ----------------------------------------------------------------
    - name: Build
      run: cmake --build --preset ${{ matrix.build-preset }}

    # ----------------------------------------------------------------
    # 4. Test (Optional)
    # If you have tests enabled, this uses the testPresets
    # ----------------------------------------------------------------
    - name: Test
      # We assume the test preset name matches the build preset name
      # If your CMakeLists.txt has enable_testing(), this runs ctest
      run: ctest --preset ${{ matrix.build-preset }} --output-on-failure